[package]
name = "crispyr"
version = "0.2.0"
authors = ["Mikkel Schubert <miksch@biosustain.dtu.dk>"]
edition = "2018"

[dependencies]
bio = "0.31.0"
bio-types = "0.5.1"
byteorder = "1.3.2"
clap = "2.33.0"
error-chain = "0.12.1"
indicatif = "0.12.0"
lazy_static = "1.4.0"
rayon = "1.2.0"
